# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_g.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

# class Ui_MainWindow(QtWidgets.QMainWindow):
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setToolTip("")
        MainWindow.setToolTipDuration(3)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 251, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 780, 480))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setToolTip("")
        self.menu.setWhatsThis("")
        self.menu.setToolTipsVisible(True)
        self.menu.setObjectName("menu")
        self.helpMenu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.helpMenu.setFont(font)
        self.helpMenu.setObjectName("helpMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBar.setFont(font)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.btnQuit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnQuit.setFont(font)
        self.btnQuit.setObjectName("btnQuit")
        self.refresh_list = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.refresh_list.setFont(font)
        self.refresh_list.setObjectName("refresh_list")
        self.history_list = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.history_list.setFont(font)
        self.history_list.setObjectName("history_list")
        self.settings_server = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settings_server.setFont(font)
        self.settings_server.setObjectName("settings_server")
        self.menu.addAction(self.refresh_list)
        self.menu.addAction(self.history_list)
        self.menu.addAction(self.settings_server)
        self.menu.addSeparator()
        self.menu.addAction(self.btnQuit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())
        self.toolBar.addAction(self.refresh_list)
        self.toolBar.addAction(self.history_list)
        self.toolBar.addAction(self.settings_server)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.btnQuit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Messaging server alfa version"))
        self.label.setText(_translate("MainWindow", "Список подключённых клиентов"))
        self.menu.setTitle(_translate("MainWindow", "Команды"))
        self.helpMenu.setTitle(_translate("MainWindow", "Помощь"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.btnQuit.setText(_translate("MainWindow", "Выход"))
        self.refresh_list.setText(_translate("MainWindow", "Обновить список"))
        self.history_list.setText(_translate("MainWindow", "История клиентов"))
        self.settings_server.setText(_translate("MainWindow", "Параметры"))

